---
config:
  layout: dagre
  theme: redux
  look: classic
---
flowchart TB
    n1["ウェブアプリ、封解Box訪問(fukaibox.kanjousekai.jp)"] --> n2["ログイン画面"]
    n2 -- Discordログイン --> n3["Discordログイン"]
    n2 -- IDログイン --> n4["ゲストログイン<br>（パスワード/ユーザー名）"]
    n3 --> n5["儀長？<br>（アカウントID確認）"]
    n5 -- Yes --> n6["儀長ロール"]
    n5 -- No --> n7["儀員？<br>（ロール確認）"]
    n7 -- Yes --> n8["儀員ロール"]
    n7 -- No --> n9["ゲストロール"]
    n4 -- 成功 --> n9
    n4 -- 失敗 --> n1
    n9 --> n10["ホーム画面"]
    n6 --> n10
    n8 --> n13["名誉儀員?<br>"]
    n13 -- Yes --> n14["名誉儀員ロール"]
    n13 -- No --> n10
    n14 --> n10
    n12["儀長ロール？"] -- Yes --> n16["儀長が料理開始"]
    n16 --> n17["調理タブ<br>(セクション分けできる・セクションごとに画像指示可能・セクションごとに参考画像up可能・儀長が推敲する・儀長は画像提出できないセクションも作成可能・儀員は推敲提案可能・儀長は推敲提案を承認/非承認)"]
    n17 --> n18["調理(推敲)完了"] & n83["AI評価(第三者としてGLM-4.6V-Flashからのショート動画の台本としての評価/採点(100点満点,厳しめ,5視点から)/伸び度/4秒でひきつけられるか/セクションごとのテンポは良いか)"]
    n19["画像upタブ<br>(セクションごとにup,upするごとに点数が上がる・アセットレジストリから持ってくることも可能)"] --> n20["画像up完了<br>(儀長が判断)"]
    n18 --> n19
    n12 -- No --> n21["待機"]
    n21 --> n18
    n20 --> n22["画像採用タブ<br>(セクションごとに儀長が暫定選定(複数可能)・儀員は何が暫定採用されたか見れる・採用されるごとに点数up)"]
    n22 --> n23["ダウンロードタブ"]
    n23 --> n24["儀長がダウンロード"]
    n11["封解Box 台所(ホーム画面のサイドバーに表示)"] --> n25["料理一覧画面"]
    n25 --> n12
    n24 --> n26["料理アーカイブ<br>(儀員はGdriveへ保存も可能)"]
    n26 --> n75["儀長?"]
    n27["情報反映ボタンが押された"] --> n28["環状世界wiki<br>https://kanjou.miraheze.org/wiki/封解公儀:原稿/[年]/[月]に原稿を自動書き込み"] & n80["台本をもとにAI(GLM-4.6V-Flash)で単語を界域百科事典に追加"] & n90["儀長に最終採用した画像を選ばせる。儀長は画像upすることもできる"]
    n30["儀員点数APIが呼び出された（この機能はスタンドアローンにする。本体から切り離す）"] -- Yes --> n62["接続認証が通った？"]
    n32["Youtube儀長チャンネルでライブ配信が開始された<br>https://www.youtube.com/@tokinohiroba"] --> n33["ホーム画面に掲載"]
    n34["封解Box 設定(ホーム画面のサイドバーの最下部に表示)"] --> n35["ユーザー設定"] & n40["儀長?"]
    n40 -- Yes --> n36["DevStudio"] & n41["AdminPanel"]
    n10 --> n11 & n34 & n63["封解Box Tools(ホーム画面のサイドバーの最下部に表示)"] & n67["界域百科事典(ホーム画面のサイドバーに表示)"] & n93["ホーム画面ウィジェット"] & n100["儀長?"]
    n46["Appを参照・実行"] --> n47["Appに高評価/低評価/コメントできる"] & n84["右サイドバーで実行"]
    n36 --> n48["儀員点数APIキー発行"] & n61["API仕様確認"]
    n31["呼び出されたエンドポイント"] --> n52["点数取得"] & n53["順位を取得"] & n54["順位から取得"] & n55["APIキーがあっている？"] & n51["ヘルスチェック"]
    n41 --> n58["儀員点数の履歴"] & n59["儀員点数の増減"] & n66["ユーザーの追放"]
    n62 -- Yes --> n31
    n55 --> n56["点数の増減"]
    n63 --> n64["Appを埋め込み/リンクとして登録(儀員/儀長のみ)"] & n65["Gallary"] & n85["封解Box Tools工房<br>AppをReactファイル/HTMLファイルとして登録 複数ファイル可能(儀員/儀長のみ)"]
    n64 --> n45["Toolsに保存・追加"]
    n65 --> n46 & n86["各カテゴリ"]
    n67 --> n74["界域百科事典ホーム"]
    n70["検索"] --> n72["単語について表示（下のほうに関連した単語を表示）"]
    n69["ジャンルごとに表示"] --> n72
    n71["年表から表示"] --> n72
    n72 --> n73["関連した単語"]
    n74 --> n71 & n70 & n69
    n75 --> n76["投稿予約ボタンが押された?"] & n27
    n76 -- Yes --> n77["儀長が日付指定・動画upしてYoutube自動予約"]
    n77 --> n78["投稿予約日がかぶった?"]
    n78 -- Yes --> n79["元々その日の予定だったものを一個後にもっていく"]
    n79 --> n78
    n78 -- No --> n81["予約完了通知"]
    n62 -- No --> n30
    n80 --> n82["情報反映通知"]
    n28 --> n82
    n83 --> n18
    n85 --> n88["AIモード?クレジット残ってる?"]
    n86 --> n46
    n84 --> n47
    n87["Qwen3 coder(openrouter経由)で作成・補正"] --> n45
    n88 -- Yes --> n87
    n88 -- No --> n45
    n45 --> n89["公開設定"]
    n89 --> n63
    n90 --> n91["GLM-4.6V-Flashに画像解析させて各画像ごとの名前を付けさせる"]
    n91 --> n92["儀長が承認"]
    n92 --> n29@{ label: "環状世界wiki<br>https://kanjou.miraheze.org/wiki/<span class=\"mw-page-title-namespace\">封解公儀</span><span class=\"mw-page-title-separator\">:</span><span class=\"mw-page-title-main\">使用素材</span>/[年]/[月]に最終採用画像を自動書き込み" }
    n21 -- 推敲提案 --> n17
    n93 --> n32 & n94["ランキングトップ3/自分の順位"] & n95["今日の名誉儀員"] & n50["Youtube封解公儀チャンネルの最新ショート動画https://www.youtube.com/@fukaikougi/shorts"]
    n35 --> n96["Discord連携設定"] & n97["GoogleDrive連携設定"] & n98["通知設定"] & n99["ユーザー名/パスワード"]
    n29 --> n82
    n100 --> n101["YoutubeManager"]
    n101 --> n102["アナリティクスタブ"] & n103["予約投稿タブ"]
    n103 --> n104["予約変更"]
    n102 --> n105["番号名前日付曜日更新日動画尺文字数再生回数コメント数高評価数低評価数登録者数エンゲージ ビューユニーク視聴者数総再生時間(時間)平均視聴時間視聴を継続スワイプして消去確かめ算未登録者数登録済み者数確かめ算女性男性確かめ算女性比男性比未登録者登録済み視聴を継続スワイプして消去視聴を継続スワイプして消去継続千回と再生回数二千回高評価率（低評価比）低評価率高評価率(再生比)高評価値（下限）低評価率(再生比)低評価値（上限）安全度健全度総合評価総合評価分類文字数評価←評価文動画尺評価←評価文視聴維持率(一人当たりの長さ)対表示率(エンゲージ)対表示率実質エンゲージ率リピート率登録率（再生全体比）登録率(未登録再生比率)偏差値（再生回数）"]
    n73 -- 戻るボタン --> n72
    n2 -- ログインせずに続行 --> n106["未ログインロール"]
    n106 --> n10

    n1@{ shape: rounded}
    n2@{ shape: diam}
    n4@{ shape: diam}
    n5@{ shape: diam}
    n6@{ shape: rect}
    n7@{ shape: diam}
    n8@{ shape: rect}
    n10@{ shape: rounded}
    n13@{ shape: diam}
    n12@{ shape: diam}
    n16@{ shape: diam}
    n18@{ shape: diam}
    n19@{ shape: rect}
    n20@{ shape: diam}
    n11@{ shape: rounded}
    n25@{ shape: rect}
    n75@{ shape: diam}
    n27@{ shape: diam}
    n30@{ shape: diam}
    n62@{ shape: diam}
    n32@{ shape: diam}
    n33@{ shape: rect}
    n34@{ shape: rounded}
    n35@{ shape: rect}
    n40@{ shape: diam}
    n63@{ shape: rounded}
    n67@{ shape: rounded}
    n100@{ shape: diam}
    n31@{ shape: diam}
    n55@{ shape: diam}
    n76@{ shape: diam}
    n78@{ shape: diam}
    n88@{ shape: diam}
    n29@{ shape: rect}
    n50@{ shape: rect}
    n105@{ shape: rect}